--- 
blank_issues_enabled: false
contact_links: 
  - 
    about: "Alternatively, you can use the Crime Time Cops & Robbers Official Discord."
    name: "Discord Support"
    url: "https://discord.gg/t7rqyAp2cr"
  - 
